# Generated by Django 4.1 on 2023-06-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10)),
                ('fare', models.IntegerField()),
                ('sum_salary', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayrollApp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('student1_1', models.CharField(max_length=10, null=True)),
                ('student1_2', models.CharField(max_length=10, null=True)),
                ('student2_1', models.CharField(max_length=10, null=True)),
                ('student2_2', models.CharField(max_length=10, null=True)),
                ('student3_1', models.CharField(max_length=10, null=True)),
                ('student3_2', models.CharField(max_length=10, null=True)),
                ('student4_1', models.CharField(max_length=10, null=True)),
                ('student4_2', models.CharField(max_length=10, null=True)),
                ('class_time', models.FloatField(null=True)),
                ('PS2_time', models.FloatField(null=True)),
                ('high12_time', models.IntegerField(null=True)),
                ('high3_time', models.IntegerField(null=True)),
                ('unit_test', models.IntegerField(null=True)),
                ('test_review', models.IntegerField(null=True)),
                ('others', models.FloatField(null=True)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayrollApp.teachers')),
            ],
        ),
    ]
